const MASTER_NODE_CONSTANTS = Object.freeze({
    MANAGERS: {
        CLIENTS: 'CLIENT_MANAGER',
        DEVICES: 'DEVICE_MANAGER',
        NOTIFY_CONDITIONS: 'NOTIFY_CONDITION_MANAGER',
        SERVICES: 'SERVICE_MANAGER'
    },
    TOPIC_DATA_BUFFER: 'TOPIC_DATA_BUFFER'
});

module.exports = MASTER_NODE_CONSTANTS;