const PING_MESSAGE = 'PING';
const PONG_MESSAGE = 'PONG';

module.exports = {
  DEFAULT_PORT_SERVICE_ZMQ: 8101,
  DEFAULT_PORT_SERVICE_REST: 8102,
  DEFAULT_PORT_TOPICDATA_ZMQ: 8103,
  DEFAULT_PORT_TOPICDATA_WS: 8104,
  DEFAULT_USE_HTTPS: true,
  PING_MESSAGE: PING_MESSAGE,
  PONG_MESSAGE: PONG_MESSAGE
};
